version: "3"
services:
  wss:
    build: .
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    env_file:
      - .env
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
